apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pull-app
  labels: 
    environment: dev
    app: secret-pull-app
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      app: secret-pull-app
  template:
    metadata:
      labels:
        environment: dev
        app: secret-pull-app
    spec:
      containers:
      - name: secret-pull-app
        image: gcr.io/infra-cicd-279015/secret-pull-app
        ports:
        - containerPort: 8080
